apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    name: app2
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app2
      tier: frontend
  template:
    metadata:
      labels:
        name: app2
        tier: frontend
    spec:
      containers:
        - name: nginx
          # image: nginx:stable-perl
          image: kdprasad028/app2:v1

---
apiVersion: v1
kind: Service
metadata:
  name: app-2
spec:
  selector:
    name: app2
    tier: frontend
  ports:
    - name: nginx-svc-port
      protocol: TCP
      port: 80
      targetPort: 80
---
#Adding ingress controler, name itself ingress,. 
apiVersion: networking.k8s.io/v1
kind: Ingress   
metadata:
    name: app2
    annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:537124943253:certificate/bad22ba1-69d0-4288-8991-5c7327645adf #create certificate for Domain:*.telugudevops.online
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
        alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
        alb.ingress.kubernetes.io/group.name: expense
spec:
    rules:
    - host: "app2.telugudevops.online"
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: app-2
              port:
                number: 80


#Kubectl apply -f manifest.yaml

#Kubectl get ingress
#Ans:  CREATED 2 hosts(app1.telugudevops.online, app2.telugudevops.online) and  two ingresses with same LB will created
