FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/index.html
RUN echo "<h1>Hello, This is from APP 1</h1>" > /usr/share/nginx/html/index.html


#BUILD dockerfile
#docker build -t kdprasad028/app1:v1 .
#docker login -u kdprasad028
#docker push kdprasad028/app1:v1

